name: 'PR Changes Requested Labeler'
description: 'Automatically labels pull requests when any reviewer requests changes'

branding:
  icon: 'tag'
  color: 'orange'

runs:
  using: 'composite'
  steps:
    - name: Add label when changes requested
      if: github.event.review.state == 'changes_requested'
      uses: actions/github-script@v7
      with:
        script: |
          await github.rest.issues.addLabels({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.payload.pull_request.number,
            labels: ['changes-requested']
          });

          console.log(`Label 'changes-requested' added to PR #${context.payload.pull_request.number}`);

    - name: Convert PR to Draft on changes requested
      if: github.event.review.state == 'changes_requested' && github.event.pull_request.draft == false
      uses: actions/github-script@v7
      with:
        script: |
          const owner = context.repo.owner;
          const repo = context.repo.repo;
          const pull_number = context.payload.pull_request.number;
          await github.request('POST /repos/{owner}/{repo}/pulls/{pull_number}/convert_to_draft', {
            owner,
            repo,
            pull_number
          });
