name: 'PR Dev Review Labeler'
description: 'Automatically labels PRs when dev reviewers request changes, excluding QA team members'

branding:
  icon: 'tag'
  color: 'orange'

runs:
  using: 'composite'
  steps:
    - name: Add label when changes requested
      if: github.event.review.state == 'changes_requested'
      uses: actions/github-script@v7
      with:
        script: |
          await github.rest.issues.addLabels({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.payload.pull_request.number,
            labels: ['dev-changes-requested']
          });

          console.log(`Label 'dev-changes-requested' added to PR #${context.payload.pull_request.number}`);

    - name: Remove label when approved
      if: github.event.review.state == 'approved'
      uses: actions/github-script@v7
      with:
        script: |
          await github.rest.issues.removeLabel({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.payload.pull_request.number,
            name: 'dev-changes-requested'
          });

          console.log(`Label removed from PR #${context.payload.pull_request.number}`);
